###
### Bolt Forms
###

# Global templates used for rendering forms and emails.
templates:
  form: boltforms_form.twig
  email: boltforms_email.twig
  subject: boltforms_email_subject.twig
  files: boltforms_file_browser.twig

# reCAPTCHa set up
recaptcha:
  enabled: false
  label: "Please enter the reCaptcha text to prove you're a human"
  public_key: ''
  private_key: ''
  error_message: "The CAPTCHA wasn't entered correctly. Please try again."
  theme: clean

## CSRF protection
#
# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

## File Uploads
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Handling file uploads is a very common attack vector used to compromise (hack)
# a server.
#
# BoltForms does a few things to help increase slightly the security of handling
# file uploads.
#
# Firstly, the directory that you specify for "base_directory" below should NOT 
# be an route accessible to the outside world. We provide a special route should
# you wish to make the files browsable after upload. 
# 
# Secondly, is the "filename_handling" parameter. If an attacker knows the 
# uploaded file name, this can make their job a bit easier. So we provide three
# options, e.g. uploading the file kitten.jpg:
#
# -------------------------------------
# | Setting | Resulting file name     |
# |-----------------------------------|
# | prefix  | kitten.Ze1d352rrI3p.jpg |
# | suffix  | kitten.jpg.Ze1d352rrI3p |
# | keep    | kitten.jpg              |
# -------------------------------------
#  
# We recommend "suffix" as this is the most secure, alternatively "prefix" will
# aid in file browsing. However "keep" should always be used with caution!
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
uploads:
  enabled: true                                  # The global on/off switch for upload handling
  base_directory: /home/maneuver/ftp/WWW/architekt/app/mail-uploads         # Outside web root and writable by the web server's user
  filename_handling: suffix                      # Can be either "prefix", "suffix", or "keep"
  management_controller: false                   # Enable a controller to handle browsing and downloading of uploaded files

## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.  However, when disabled an individual
# form can still enable it's own debug — specific for and to that form
debug:
  enabled: false
  address: biuro@maneuver.pl

## Example 1
#
## Contact Form
#contact:
#  notification:
#    enabled: true
#    debug: true
#    subject: Your message was submitted
#    from_name: name               # A field name, specified in the fields: section below
#    from_email: email             # A field name, specified in the fields: section below
#    replyto_name: name            # A field name, specified in the fields: section below
#    replyto_email: email          # A field name, specified in the fields: section below
#    to_name: My Site              # Must be valid text
#    to_email: noreply@example.com # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
#    attach_files: false
#  feedback:
#    success: Message submission successful
#    error: There are errors in the form, please fix before trying to resubmit
##  database:
##    contenttype: mycontenttype  # ContentType record to create
##    table: bolt_secret_table    # Specific database table to write to
#  fields:
#    name:
#      type: text
#      options:
#        required: true
#        label: Name
#        attr:
#          placeholder: Your name...
#        constraints: [ NotBlank, {Length: {'min': 3}} ]
#    email:
#      type: email
#      options:
#        required: true
#        label: Email address
#        attr:
#          placeholder: Your email...
#        constraints: [ NotBlank, Email ]
#    message:
#      type: textarea
#      options:
#        required: true
#        label: Your message
#        attr:
#          placeholder: Your message...
#          class: myclass
#    needreply:
#      type: choice
#      options:
#        required: false
#        label: Do you want us to contact you back?
#        choices: [ Yes, No ]
#        multiple: false
#    submit:
#      type: submit

# Custom Contact Form
contact_pl:
  notification:
    enabled: true
    debug: false
    subject: Formularz kontaktowy ze strony
    from_name: name               # A field name, specified in the fields: section below
    from_email: formularz@mikolajskastudio.pl             # A field name, specified in the fields: section below
    replyto_name: name            # A field name, specified in the fields: section below
    replyto_email: email          # A field name, specified in the fields: section below
    to_name: Mikołajska Studio              # Must be valid text
    to_email: kontakt@mikolajskastudio.pl      # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
    attach_files: false
  feedback:
    success: Twoja wiadomość została pomyślnie wysłana.
    error: Formularz posiada błędy, napraw je i spróbuj wysłać ponownie.
#  database:
#    contenttype: mycontenttype  # ContentType record to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    name:
      type: text
      options:
        required: true
        attr:
          placeholder: Imię i nazwisko
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        attr:
          placeholder: Email
        constraints: [ NotBlank, Email ]
    message:
      type: textarea
      options:
        required: true
        attr:
          placeholder: Wiadomość
          class: myclass
    submit:
      type: submit
      options:
        label: WYŚLIJ
  templates:
    form: modules/_contact_form.twig

apply_pl:
  notification:
    enabled: true
    debug: false
    subject: Aplikacja o pracę ze strony
    from_name: name               # A field name, specified in the fields: section below
    from_email: formularz@mikolajskastudio.pl # A field name, specified in the fields: section below
    replyto_name: name            # A field name, specified in the fields: section below
    replyto_email: email          # A field name, specified in the fields: section below
    to_name: Mikołajska Studio              # Must be valid text
    to_email: kontakt@mikolajskastudio.pl # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
    attach_files: true
  feedback:
    success: Twoja wiadomość została pomyślnie wysłana.
    error: Formularz posiada błędy, napraw je i spróbuj wysłać ponownie.
#  database:
#    contenttype: mycontenttype  # ContentType record to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    name:
      type: text
      options:
        required: true
        attr:
          placeholder: Imię i nazwisko
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        attr:
          placeholder: Email
        constraints: [ NotBlank, Email ]
    cv:
      type: file
      options:
        required: false
        label: CV
        attr:
            class: upload
    cover_letter:
      type: file
      options:
        required: false
        label: List motywacyjny
        attr:
          class: upload
    submit:
      type: submit
      options:
        label: WYŚLIJ
  templates:
    form: modules/_apply_form.twig

# ENG FORMS ------------------------------------------------------------------------------------------------------------

contact_en:
  notification:
    enabled: true
    debug: false
    subject: Kontakt ze strony www
    from_name: name               # A field name, specified in the fields: section below
    from_email: formularz@mikolajskastudio.pl             # A field name, specified in the fields: section below
    replyto_name: name            # A field name, specified in the fields: section below
    replyto_email: email          # A field name, specified in the fields: section below
    to_name: Mikołajska Studio              # Must be valid text
    to_email: kontakt@mikolajskastudio.pl      # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
    attach_files: false
  feedback:
    success: Twoja wiadomość została pomyślnie wysłana.
    error: Formularz posiada błędy, napraw je i spróbuj wysłać ponownie.
#  database:
#    contenttype: mycontenttype  # ContentType record to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    name:
      type: text
      options:
        required: true
        attr:
          placeholder: Name and Surname
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        attr:
          placeholder: Email
        constraints: [ NotBlank, Email ]
    message:
      type: textarea
      options:
        required: true
        attr:
          placeholder: Message
          class: myclass
    submit:
      type: submit
      options:
        label: SEND
  templates:
    form: modules/_contact_form.twig

apply_en:
  notification:
    enabled: true
    debug: false
    subject: Aplikacja o pracę ze strony
    from_name: name               # A field name, specified in the fields: section below
    from_email: formularz@mikolajskastudio.pl # A field name, specified in the fields: section below
    replyto_name: name            # A field name, specified in the fields: section below
    replyto_email: email          # A field name, specified in the fields: section below
    to_name: Mikołajska Studio              # Must be valid text
    to_email: kontakt@mikolajskastudio.pl # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
    attach_files: true
  feedback:
    success: Message submission successful.
    error: There are errors in the form, please fix before trying to resubmit.
#  database:
#    contenttype: mycontenttype  # ContentType record to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    name:
      type: text
      options:
        required: true
        attr:
          placeholder: Name and Surname
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        attr:
          placeholder: Email
        constraints: [ NotBlank, Email ]
    cv:
      type: file
      options:
        required: false
        label: CV
        attr:
            class: upload
    cover_letter:
      type: file
      options:
        required: false
        label: Cover Letter
        attr:
          class: upload
    submit:
      type: submit
      options:
        label: SEND
  templates:
    form: modules/_apply_form.twig

## Example 2
#
# Example Showcase Form
#showcase:
#  notification:
#    enabled: true
#    debug: false
#    subject: "[TESTING] A showcase form was just submitted" 
#    from_name: name               # A field name, specified in the fields: section below
#    replyto_email: email          # A field name, specified in the fields: section below
#    replyto_name: name            # A field name, specified in the fields: section below
#    from_email: email             # A field name, specified in the fields: section below
#    to_name: My Site              # Must be valid text
#    to_email: noreply@example.com # Must be valid email address
#    cc_name: Info Person
#    cc_email: info@example.com
#    bcc_name: Manager Person
#    bcc_email: manager@example.com
#    attach_files: false
#  templates:                      # Over ride the global Twig templates for this form
#    form: boltforms_form.twig
#    email: boltforms_email.twig
#    subject: boltforms_email_subject.twig
#  feedback:
#    success: Form submission sucessful
#    error: There are errors in the form, please fix before trying to resubmit
#    redirect:
#      target: page/another-page  # A page path, or URL
#      query: [ name, email ]     # Optional keys for the GET parameters
#  database:
#    contenttype: mycontenttype  # ContentType record to create
#    table: bolt_secret_table    # Specific database table to write to
#  uploads:
#    subdirectory: showcase_files # The (optional) subdirectory for uploaded files 
#  fields:
#    subject:
#      type: text
#      options:
#        required: true
#        label: Subject of your message
#        attr:
#          placeholder: Just a quick message...
#        constraints: [ NotBlank, {Length: {'min': 3, 'max': 30}} ]
#    name:
#      type: text
#      options:
#        required: true
#        label: Name
#        attr:
#          placeholder: Your name...
#        constraints: [ NotBlank, {Length: {'min': 3}} ]
#    email:
#      type: email
#      options:
#        required: true
#        label: Email address
#        attr:
#          placeholder: Your email...
#          class: myclass-email
#        constraints: [ NotBlank, Email ]
#    message:
#      type: textarea
#      options:
#        required: true
#        label: Your message
#        attr:
#          placeholder: Well, the other day I was thinking that maybe you ought to improve your website by adding...
#          class: myclass-message
#    pet_ownership:
#      type: choice
#      options:
#        required: false
#        label: Do you own a pet?
#        choices: [ Yes, No ]
#        multiple: false
#    cutest_pet:
#      type: choice
#      options:
#        required: false
#        label: Which do you think are cutest?
#        choices: { kittens: 'Fluffy Kittens', puppies: 'Cute Puppies' }
#    best_pet_page:
#      type: choice
#      options:
#        required: false
#        label: What is our best pets page?
#        choices: 'contenttype::pets::title::slug'
#    upload:
#      type: file
#      options:
#        required: false
#        label: Picture of your pet that you want us to add to our site
#    submit:
#      type: submit
